/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::types;
use serde::{Deserialize, Serialize};

/// EquityResponse : Quote info of Equity security
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EquityResponse {
    #[serde(rename = "assetMainType", skip_serializing_if = "Option::is_none")]
    pub asset_main_type: Option<types::AssetMainType>,
    #[serde(
        rename = "assetSubType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub asset_sub_type: Option<Option<types::EquityAssetSubType>>,
    /// SSID of instrument
    #[serde(rename = "ssid", skip_serializing_if = "Option::is_none")]
    pub ssid: Option<i64>,
    /// Symbol of instrument
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// is quote realtime
    #[serde(rename = "realtime", skip_serializing_if = "Option::is_none")]
    pub realtime: Option<bool>,
    #[serde(
        rename = "quoteType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub quote_type: Option<Option<types::QuoteType>>,
    #[serde(rename = "extended", skip_serializing_if = "Option::is_none")]
    pub extended: Option<Box<types::ExtendedMarket>>,
    #[serde(rename = "fundamental", skip_serializing_if = "Option::is_none")]
    pub fundamental: Option<Box<types::Fundamental>>,
    #[serde(rename = "quote", skip_serializing_if = "Option::is_none")]
    pub quote: Option<Box<types::QuoteEquity>>,
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<Box<types::ReferenceEquity>>,
    #[serde(rename = "regular", skip_serializing_if = "Option::is_none")]
    pub regular: Option<Box<types::RegularMarket>>,
}

impl EquityResponse {
    /// Quote info of Equity security
    pub fn new() -> EquityResponse {
        EquityResponse {
            asset_main_type: None,
            asset_sub_type: None,
            ssid: None,
            symbol: None,
            realtime: None,
            quote_type: None,
            extended: None,
            fundamental: None,
            quote: None,
            reference: None,
            regular: None,
        }
    }
}
