/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::types;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMovers200Response {
    #[serde(rename = "screeners", skip_serializing_if = "Option::is_none")]
    pub screeners: Option<Vec<types::Screener>>,
}

impl GetMovers200Response {
    pub fn new() -> GetMovers200Response {
        GetMovers200Response { screeners: None }
    }
}
