/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::types;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteResponseObject {
    EquityResponse(Box<types::EquityResponse>),
    OptionResponse(Box<types::OptionResponse>),
    ForexResponse(Box<types::ForexResponse>),
    FutureResponse(Box<types::FutureResponse>),
    FutureOptionResponse(Box<types::FutureOptionResponse>),
    IndexResponse(Box<types::IndexResponse>),
    MutualFundResponse(Box<types::MutualFundResponse>),
    QuoteError(Box<types::QuoteError>),
}

impl Default for QuoteResponseObject {
    fn default() -> Self {
        Self::EquityResponse(Default::default())
    }
}
