/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::types;
use serde::{Deserialize, Serialize};

/// ReferenceFutureOption : Reference data of Future Option security
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferenceFutureOption {
    #[serde(rename = "contractType", skip_serializing_if = "Option::is_none")]
    pub contract_type: Option<types::ContractType>,
    /// Description of Instrument
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Exchange Code
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// Exchange Name
    #[serde(rename = "exchangeName", skip_serializing_if = "Option::is_none")]
    pub exchange_name: Option<String>,
    /// Option multiplier
    #[serde(rename = "multiplier", skip_serializing_if = "Option::is_none")]
    pub multiplier: Option<f64>,
    /// date of expiration in long
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<i64>,
    /// Style of expiration
    #[serde(rename = "expirationStyle", skip_serializing_if = "Option::is_none")]
    pub expiration_style: Option<String>,
    /// Strike Price
    #[serde(rename = "strikePrice", skip_serializing_if = "Option::is_none")]
    pub strike_price: Option<f64>,
    /// A company, index or fund name
    #[serde(rename = "underlying", skip_serializing_if = "Option::is_none")]
    pub underlying: Option<String>,
}

impl ReferenceFutureOption {
    /// Reference data of Future Option security
    pub fn new() -> ReferenceFutureOption {
        ReferenceFutureOption {
            contract_type: None,
            description: None,
            exchange: None,
            exchange_name: None,
            multiplier: None,
            expiration_date: None,
            expiration_style: None,
            strike_price: None,
            underlying: None,
        }
    }
}
