/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EquityAssetSubType : Asset Sub Type (only there if applicable)
/// Asset Sub Type (only there if applicable)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EquityAssetSubType {
    #[serde(rename = "COE")]
    Coe,
    #[serde(rename = "PRF")]
    Prf,
    #[serde(rename = "ADR")]
    Adr,
    #[serde(rename = "GDR")]
    Gdr,
    #[serde(rename = "CEF")]
    Cef,
    #[serde(rename = "ETF")]
    Etf,
    #[serde(rename = "ETN")]
    Etn,
    #[serde(rename = "UIT")]
    Uit,
    #[serde(rename = "WAR")]
    War,
    #[serde(rename = "RGT")]
    Rgt,
}

impl std::fmt::Display for EquityAssetSubType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Coe => write!(f, "COE"),
            Self::Prf => write!(f, "PRF"),
            Self::Adr => write!(f, "ADR"),
            Self::Gdr => write!(f, "GDR"),
            Self::Cef => write!(f, "CEF"),
            Self::Etf => write!(f, "ETF"),
            Self::Etn => write!(f, "ETN"),
            Self::Uit => write!(f, "UIT"),
            Self::War => write!(f, "WAR"),
            Self::Rgt => write!(f, "RGT"),
        }
    }
}

impl Default for EquityAssetSubType {
    fn default() -> EquityAssetSubType {
        Self::Coe
    }
}
