/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::marketdata;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpirationChain {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "expirationList", skip_serializing_if = "Option::is_none")]
    pub expiration_list: Option<Vec<marketdata::Expiration>>,
}

impl ExpirationChain {
    pub fn new() -> ExpirationChain {
        ExpirationChain {
            status: None,
            expiration_list: None,
        }
    }
}
