/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// QuoteError : Partial or Custom errors per request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteError {
    /// list of invalid cusips from request
    #[serde(rename = "invalidCusips", skip_serializing_if = "Option::is_none")]
    pub invalid_cusips: Option<Vec<String>>,
    /// list of invalid SSIDs from request
    #[serde(rename = "invalidSSIDs", skip_serializing_if = "Option::is_none")]
    pub invalid_ssids: Option<Vec<i64>>,
    /// list of invalid symbols from request
    #[serde(rename = "invalidSymbols", skip_serializing_if = "Option::is_none")]
    pub invalid_symbols: Option<Vec<String>>,
}

impl QuoteError {
    /// Partial or Custom errors per request
    pub fn new() -> QuoteError {
        QuoteError {
            invalid_cusips: None,
            invalid_ssids: None,
            invalid_symbols: None,
        }
    }
}
