/*
 * Market Data
 *
 * Trader API - Market data
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::marketdata;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuoteResponseObject {
    EquityResponse(Box<marketdata::EquityResponse>),
    OptionResponse(Box<marketdata::OptionResponse>),
    ForexResponse(Box<marketdata::ForexResponse>),
    FutureResponse(Box<marketdata::FutureResponse>),
    FutureOptionResponse(Box<marketdata::FutureOptionResponse>),
    IndexResponse(Box<marketdata::IndexResponse>),
    MutualFundResponse(Box<marketdata::MutualFundResponse>),
    QuoteError(Box<marketdata::QuoteError>),
}

impl Default for QuoteResponseObject {
    fn default() -> Self {
        Self::EquityResponse(Default::default())
    }
}
