/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "securitiesAccount", skip_serializing_if = "Option::is_none")]
    pub securities_account: Option<Box<trader::SecuritiesAccount>>,
}

impl Account {
    pub fn new() -> Account {
        Account {
            securities_account: None,
        }
    }
}
