/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "assetType")]
pub enum AccountsInstrument {
    #[serde(rename = "CASH_EQUIVALENT")]
    CashEquivalent(Box<trader::AccountCashEquivalent>),
    #[serde(rename = "EQUITY")]
    Equity(Box<trader::AccountEquity>),
    #[serde(rename = "FIXED_INCOME")]
    FixedIncome(Box<trader::AccountFixedIncome>),
    #[serde(rename = "MUTUAL_FUND")]
    MutualFund(Box<trader::AccountMutualFund>),
    #[serde(rename = "OPTION")]
    Option(Box<trader::AccountOption>),
}

impl Default for AccountsInstrument {
    fn default() -> Self {
        Self::CashEquivalent(Default::default())
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "SWEEP_VEHICLE")]
    SweepVehicle,
    #[serde(rename = "SAVINGS")]
    Savings,
    #[serde(rename = "MONEY_MARKET_FUND")]
    MoneyMarketFund,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "VANILLA")]
    Vanilla,
    #[serde(rename = "BINARY")]
    Binary,
    #[serde(rename = "BARRIER")]
    Barrier,
}

impl Default for Type {
    fn default() -> Type {
        Self::SweepVehicle
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PutCall {
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "CALL")]
    Call,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for PutCall {
    fn default() -> PutCall {
        Self::Put
    }
}
