/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountNumberHash {
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "hashValue", skip_serializing_if = "Option::is_none")]
    pub hash_value: Option<String>,
}

impl AccountNumberHash {
    pub fn new() -> AccountNumberHash {
        AccountNumberHash {
            account_number: None,
            hash_value: None,
        }
    }
}
