/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AmountIndicator {
    #[serde(rename = "DOLLARS")]
    Dollars,
    #[serde(rename = "SHARES")]
    Shares,
    #[serde(rename = "ALL_SHARES")]
    AllShares,
    #[serde(rename = "PERCENTAGE")]
    Percentage,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for AmountIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dollars => write!(f, "DOLLARS"),
            Self::Shares => write!(f, "SHARES"),
            Self::AllShares => write!(f, "ALL_SHARES"),
            Self::Percentage => write!(f, "PERCENTAGE"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for AmountIndicator {
    fn default() -> AmountIndicator {
        Self::Dollars
    }
}
