/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashBalance {
    #[serde(
        rename = "cashAvailableForTrading",
        skip_serializing_if = "Option::is_none"
    )]
    pub cash_available_for_trading: Option<f64>,
    #[serde(
        rename = "cashAvailableForWithdrawal",
        skip_serializing_if = "Option::is_none"
    )]
    pub cash_available_for_withdrawal: Option<f64>,
    #[serde(rename = "cashCall", skip_serializing_if = "Option::is_none")]
    pub cash_call: Option<f64>,
    #[serde(
        rename = "longNonMarginableMarketValue",
        skip_serializing_if = "Option::is_none"
    )]
    pub long_non_marginable_market_value: Option<f64>,
    #[serde(rename = "totalCash", skip_serializing_if = "Option::is_none")]
    pub total_cash: Option<f64>,
    #[serde(rename = "cashDebitCallValue", skip_serializing_if = "Option::is_none")]
    pub cash_debit_call_value: Option<f64>,
    #[serde(rename = "unsettledCash", skip_serializing_if = "Option::is_none")]
    pub unsettled_cash: Option<f64>,
}

impl CashBalance {
    pub fn new() -> CashBalance {
        CashBalance {
            cash_available_for_trading: None,
            cash_available_for_withdrawal: None,
            cash_call: None,
            long_non_marginable_market_value: None,
            total_cash: None,
            cash_debit_call_value: None,
            unsettled_cash: None,
        }
    }
}
