/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommissionLeg {
    #[serde(rename = "commissionValues", skip_serializing_if = "Option::is_none")]
    pub commission_values: Option<Vec<trader::CommissionValue>>,
}

impl CommissionLeg {
    pub fn new() -> CommissionLeg {
        CommissionLeg {
            commission_values: None,
        }
    }
}
