/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommissionAndFee {
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<Box<trader::Commission>>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<Box<trader::Fees>>,
    #[serde(rename = "trueCommission", skip_serializing_if = "Option::is_none")]
    pub true_commission: Option<Box<trader::Commission>>,
}

impl CommissionAndFee {
    pub fn new() -> CommissionAndFee {
        CommissionAndFee {
            commission: None,
            fee: None,
            true_commission: None,
        }
    }
}
