/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeLeg {
    #[serde(rename = "feeValues", skip_serializing_if = "Option::is_none")]
    pub fee_values: Option<Vec<trader::FeeValue>>,
}

impl FeeLeg {
    pub fn new() -> FeeLeg {
        FeeLeg { fee_values: None }
    }
}
