/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Index {
    #[serde(rename = "activeContract", skip_serializing_if = "Option::is_none")]
    pub active_contract: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "assetType")]
    pub asset_type: AssetType,
    #[serde(rename = "cusip", skip_serializing_if = "Option::is_none")]
    pub cusip: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "instrumentId", skip_serializing_if = "Option::is_none")]
    pub instrument_id: Option<i64>,
    #[serde(rename = "netChange", skip_serializing_if = "Option::is_none")]
    pub net_change: Option<f64>,
    #[serde(rename = "maturityDate", skip_serializing_if = "Option::is_none")]
    pub maturity_date: Option<String>,
    #[serde(rename = "factor", skip_serializing_if = "Option::is_none")]
    pub factor: Option<f64>,
    #[serde(rename = "multiplier", skip_serializing_if = "Option::is_none")]
    pub multiplier: Option<f64>,
    #[serde(rename = "variableRate", skip_serializing_if = "Option::is_none")]
    pub variable_rate: Option<f64>,
    #[serde(rename = "baseCurrency", skip_serializing_if = "Option::is_none")]
    pub base_currency: Option<Box<trader::Currency>>,
    #[serde(rename = "counterCurrency", skip_serializing_if = "Option::is_none")]
    pub counter_currency: Option<Box<trader::Currency>>,
    #[serde(rename = "expirationDate", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    #[serde(rename = "lastTradingDate", skip_serializing_if = "Option::is_none")]
    pub last_trading_date: Option<String>,
    #[serde(rename = "firstNoticeDate", skip_serializing_if = "Option::is_none")]
    pub first_notice_date: Option<String>,
    #[serde(rename = "fundFamilyName", skip_serializing_if = "Option::is_none")]
    pub fund_family_name: Option<String>,
    #[serde(rename = "fundFamilySymbol", skip_serializing_if = "Option::is_none")]
    pub fund_family_symbol: Option<String>,
    #[serde(rename = "fundGroup", skip_serializing_if = "Option::is_none")]
    pub fund_group: Option<String>,
    #[serde(rename = "exchangeCutoffTime", skip_serializing_if = "Option::is_none")]
    pub exchange_cutoff_time: Option<String>,
    #[serde(rename = "purchaseCutoffTime", skip_serializing_if = "Option::is_none")]
    pub purchase_cutoff_time: Option<String>,
    #[serde(
        rename = "redemptionCutoffTime",
        skip_serializing_if = "Option::is_none"
    )]
    pub redemption_cutoff_time: Option<String>,
    #[serde(rename = "optionDeliverables", skip_serializing_if = "Option::is_none")]
    pub option_deliverables: Option<Vec<trader::TransactionApiOptionDeliverable>>,
    #[serde(
        rename = "optionPremiumMultiplier",
        skip_serializing_if = "Option::is_none"
    )]
    pub option_premium_multiplier: Option<i64>,
    #[serde(rename = "putCall", skip_serializing_if = "Option::is_none")]
    pub put_call: Option<PutCall>,
    #[serde(rename = "strikePrice", skip_serializing_if = "Option::is_none")]
    pub strike_price: Option<f64>,
    #[serde(rename = "underlyingSymbol", skip_serializing_if = "Option::is_none")]
    pub underlying_symbol: Option<String>,
    #[serde(rename = "underlyingCusip", skip_serializing_if = "Option::is_none")]
    pub underlying_cusip: Option<String>,
    #[serde(rename = "deliverable", skip_serializing_if = "Option::is_none")]
    pub deliverable: Option<Box<trader::TransactionInstrument>>,
}

impl Index {
    pub fn new(asset_type: AssetType) -> Index {
        Index {
            active_contract: None,
            r#type: None,
            asset_type,
            cusip: None,
            symbol: None,
            description: None,
            instrument_id: None,
            net_change: None,
            maturity_date: None,
            factor: None,
            multiplier: None,
            variable_rate: None,
            base_currency: None,
            counter_currency: None,
            expiration_date: None,
            last_trading_date: None,
            first_notice_date: None,
            fund_family_name: None,
            fund_family_symbol: None,
            fund_group: None,
            exchange_cutoff_time: None,
            purchase_cutoff_time: None,
            redemption_cutoff_time: None,
            option_deliverables: None,
            option_premium_multiplier: None,
            put_call: None,
            strike_price: None,
            underlying_symbol: None,
            underlying_cusip: None,
            deliverable: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "BROAD_BASED")]
    BroadBased,
    #[serde(rename = "NARROW_BASED")]
    NarrowBased,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Type {
    fn default() -> Type {
        Self::BroadBased
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssetType {
    #[serde(rename = "EQUITY")]
    Equity,
    #[serde(rename = "OPTION")]
    Option,
    #[serde(rename = "INDEX")]
    Index,
    #[serde(rename = "MUTUAL_FUND")]
    MutualFund,
    #[serde(rename = "CASH_EQUIVALENT")]
    CashEquivalent,
    #[serde(rename = "FIXED_INCOME")]
    FixedIncome,
    #[serde(rename = "CURRENCY")]
    Currency,
    #[serde(rename = "COLLECTIVE_INVESTMENT")]
    CollectiveInvestment,
}

impl Default for AssetType {
    fn default() -> AssetType {
        Self::Equity
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PutCall {
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "CALL")]
    Call,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for PutCall {
    fn default() -> PutCall {
        Self::Put
    }
}
