/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Offer {
    #[serde(rename = "level2Permissions", skip_serializing_if = "Option::is_none")]
    pub level2_permissions: Option<bool>,
    #[serde(rename = "mktDataPermission", skip_serializing_if = "Option::is_none")]
    pub mkt_data_permission: Option<String>,
}

impl Offer {
    pub fn new() -> Offer {
        Offer {
            level2_permissions: None,
            mkt_data_permission: None,
        }
    }
}
