/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "activityType")]
pub enum OrderActivity {
    #[serde(rename = "EXECUTION")]
    Execution,
    #[serde(rename = "ORDER_ACTION")]
    OrderAction,
}

impl Default for OrderActivity {
    fn default() -> OrderActivity {
        Self::Execution
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExecutionType {
    #[serde(rename = "FILL")]
    Fill,
}

impl Default for ExecutionType {
    fn default() -> ExecutionType {
        Self::Fill
    }
}
