/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBalance {
    #[serde(rename = "orderValue", skip_serializing_if = "Option::is_none")]
    pub order_value: Option<f64>,
    #[serde(
        rename = "projectedAvailableFund",
        skip_serializing_if = "Option::is_none"
    )]
    pub projected_available_fund: Option<f64>,
    #[serde(
        rename = "projectedBuyingPower",
        skip_serializing_if = "Option::is_none"
    )]
    pub projected_buying_power: Option<f64>,
    #[serde(
        rename = "projectedCommission",
        skip_serializing_if = "Option::is_none"
    )]
    pub projected_commission: Option<f64>,
}

impl OrderBalance {
    pub fn new() -> OrderBalance {
        OrderBalance {
            order_value: None,
            projected_available_fund: None,
            projected_buying_power: None,
            projected_commission: None,
        }
    }
}
