/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewOrder {
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    #[serde(rename = "orderStrategy", skip_serializing_if = "Option::is_none")]
    pub order_strategy: Option<Box<trader::OrderStrategy>>,
    #[serde(
        rename = "orderValidationResult",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_validation_result: Option<Box<trader::OrderValidationResult>>,
    #[serde(rename = "commissionAndFee", skip_serializing_if = "Option::is_none")]
    pub commission_and_fee: Option<Box<trader::CommissionAndFee>>,
}

impl PreviewOrder {
    pub fn new() -> PreviewOrder {
        PreviewOrder {
            order_id: None,
            order_strategy: None,
            order_validation_result: None,
            commission_and_fee: None,
        }
    }
}
