/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PriceLinkType {
    #[serde(rename = "VALUE")]
    Value,
    #[serde(rename = "PERCENT")]
    Percent,
    #[serde(rename = "TICK")]
    Tick,
}

impl std::fmt::Display for PriceLinkType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Value => write!(f, "VALUE"),
            Self::Percent => write!(f, "PERCENT"),
            Self::Tick => write!(f, "TICK"),
        }
    }
}

impl Default for PriceLinkType {
    fn default() -> PriceLinkType {
        Self::Value
    }
}
