/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SecuritiesAccount {
    #[serde(rename = "MARGIN")]
    Margin(Box<trader::MarginAccount>),
    #[serde(rename = "CASH")]
    Cash(Box<trader::CashAccount>),
}

impl Default for SecuritiesAccount {
    fn default() -> Self {
        Self::Margin(Default::default())
    }
}
