/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Session {
    #[serde(rename = "NORMAL")]
    Normal,
    #[serde(rename = "AM")]
    Am,
    #[serde(rename = "PM")]
    Pm,
    #[serde(rename = "SEAMLESS")]
    Seamless,
}

impl std::fmt::Display for Session {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "NORMAL"),
            Self::Am => write!(f, "AM"),
            Self::Pm => write!(f, "PM"),
            Self::Seamless => write!(f, "SEAMLESS"),
        }
    }
}

impl Default for Session {
    fn default() -> Session {
        Self::Normal
    }
}
