/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SettlementInstruction {
    #[serde(rename = "REGULAR")]
    Regular,
    #[serde(rename = "CASH")]
    Cash,
    #[serde(rename = "NEXT_DAY")]
    NextDay,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for SettlementInstruction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Regular => write!(f, "REGULAR"),
            Self::Cash => write!(f, "CASH"),
            Self::NextDay => write!(f, "NEXT_DAY"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for SettlementInstruction {
    fn default() -> SettlementInstruction {
        Self::Regular
    }
}
