/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamerInfo {
    #[serde(rename = "streamerSocketUrl", skip_serializing_if = "Option::is_none")]
    pub streamer_socket_url: Option<String>,
    #[serde(
        rename = "schwabClientCustomerId",
        skip_serializing_if = "Option::is_none"
    )]
    pub schwab_client_customer_id: Option<String>,
    #[serde(
        rename = "schwabClientCorrelId",
        skip_serializing_if = "Option::is_none"
    )]
    pub schwab_client_correl_id: Option<String>,
    #[serde(
        rename = "schwabClientChannel",
        skip_serializing_if = "Option::is_none"
    )]
    pub schwab_client_channel: Option<String>,
    #[serde(
        rename = "schwabClientFunctionId",
        skip_serializing_if = "Option::is_none"
    )]
    pub schwab_client_function_id: Option<String>,
}

impl StreamerInfo {
    pub fn new() -> StreamerInfo {
        StreamerInfo {
            streamer_socket_url: None,
            schwab_client_customer_id: None,
            schwab_client_correl_id: None,
            schwab_client_channel: None,
            schwab_client_function_id: None,
        }
    }
}
