/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "activityType")]
pub enum Transaction {
    #[serde(rename = "ACTIVITY_CORRECTION")]
    ActivityCorrection,
    #[serde(rename = "EXECUTION")]
    Execution,
    #[serde(rename = "ORDER_ACTION")]
    OrderAction,
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Transaction {
    fn default() -> Self {
        Self::ActivityCorrection
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "VALID")]
    Valid,
    #[serde(rename = "INVALID")]
    Invalid,
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Status {
    fn default() -> Self {
        Self::Valid
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubAccount {
    #[serde(rename = "CASH")]
    Cash,
    #[serde(rename = "MARGIN")]
    Margin,
    #[serde(rename = "SHORT")]
    Short,
    #[serde(rename = "DIV")]
    Div,
    #[serde(rename = "INCOME")]
    Income,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for SubAccount {
    fn default() -> Self {
        Self::Cash
    }
}
