/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPreferenceAccount {
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[serde(rename = "primaryAccount", skip_serializing_if = "Option::is_none")]
    pub primary_account: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "nickName", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<String>,
    /// Green | Blue
    #[serde(rename = "accountColor", skip_serializing_if = "Option::is_none")]
    pub account_color: Option<String>,
    #[serde(rename = "displayAcctId", skip_serializing_if = "Option::is_none")]
    pub display_acct_id: Option<String>,
    #[serde(rename = "autoPositionEffect", skip_serializing_if = "Option::is_none")]
    pub auto_position_effect: Option<bool>,
}

impl UserPreferenceAccount {
    pub fn new() -> Self {
        Self {
            account_number: None,
            primary_account: None,
            r#type: None,
            nick_name: None,
            account_color: None,
            display_acct_id: None,
            auto_position_effect: None,
        }
    }
}
