/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ADVISOR_USER")]
    AdvisorUser,
    #[serde(rename = "BROKER_USER")]
    BrokerUser,
    #[serde(rename = "CLIENT_USER")]
    ClientUser,
    #[serde(rename = "SYSTEM_USER")]
    SystemUser,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for Type {
    fn default() -> Self {
        Self::AdvisorUser
    }
}
