/*
 * Trader API - Account Access and User Preferences
 *
 * Schwab Trader API access to Account, Order entry and User Preferences
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: TraderAPI@Schwab.com
 * Generated by: https://openapi-generator.tech
 */

use crate::trader;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPreference {
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<trader::UserPreferenceAccount>>,
    #[serde(rename = "streamerInfo", skip_serializing_if = "Option::is_none")]
    pub streamer_info: Option<Vec<trader::StreamerInfo>>,
    #[serde(rename = "offers", skip_serializing_if = "Option::is_none")]
    pub offers: Option<Vec<trader::Offer>>,
}

impl UserPreference {
    pub fn new() -> Self {
        Self {
            accounts: None,
            streamer_info: None,
            offers: None,
        }
    }
}
